"""Upstream story lab v2 - transplant workspace package.

Not imported by production. Prototypes the multi-source story architecture
(banks/packs/pipelines/styles as JSON; Python validates, routes, executes,
fails loudly) and emits the bridge artifact production will consume at the
explicit transplant chunk.
"""

from .contracts import (
    BridgeArtifact,
    LedgerWritingSpec,
    MetaMirrors,
    PipelineSpec,
    PublicDomainSourceManifest,
    Resolution,
    SourceBankSpec,
    SourceMaterialPacket,
    StoryInputPacket,
    StoryPack,
    StoryPromptProfile,
    VisualStylePolicy,
)
from .registry import Registry, RegistryError, UnknownIdError
from .ledger_contract import (
    LedgerContractError,
    LedgerEnvelope,
    OutcomeReceipt,
    ReceiptVerifier,
    ReceiptVerifierKey,
    StoryBody,
    StoryLedger,
    StorySeal,
    assert_story_unchanged,
    build_story_seal,
    canonical_bytes,
    canonical_sha256,
    verify_story_acceptance,
    verify_story_envelope,
)
from .ledger_verifiers import (
    CAPTURED_SOURCE_PACKET_SCHEMA_VERSION,
    CapturedSourcePacketArtifact,
    TRUSTED_VALIDATOR_IDENTITIES,
    TRUSTED_VALIDATOR_VERSION,
    build_trusted_receipt_verifiers,
    verify_announcer_news_coda,
    verify_announcer_open,
    verify_ledger_integrity,
    verify_music_bookends,
    verify_news_capture,
)

__all__ = [
    "BridgeArtifact",
    "CAPTURED_SOURCE_PACKET_SCHEMA_VERSION",
    "CapturedSourcePacketArtifact",
    "LedgerWritingSpec",
    "LedgerContractError",
    "LedgerEnvelope",
    "MetaMirrors",
    "OutcomeReceipt",
    "PipelineSpec",
    "PublicDomainSourceManifest",
    "ReceiptVerifier",
    "ReceiptVerifierKey",
    "Registry",
    "RegistryError",
    "Resolution",
    "SourceBankSpec",
    "SourceMaterialPacket",
    "StoryInputPacket",
    "StoryBody",
    "StoryLedger",
    "StoryPack",
    "StoryPromptProfile",
    "StorySeal",
    "TRUSTED_VALIDATOR_IDENTITIES",
    "TRUSTED_VALIDATOR_VERSION",
    "UnknownIdError",
    "VisualStylePolicy",
    "assert_story_unchanged",
    "build_story_seal",
    "build_trusted_receipt_verifiers",
    "canonical_bytes",
    "canonical_sha256",
    "verify_story_acceptance",
    "verify_story_envelope",
    "verify_announcer_news_coda",
    "verify_announcer_open",
    "verify_ledger_integrity",
    "verify_music_bookends",
    "verify_news_capture",
]
