"""Upstream story lab v2 - transplant workspace package.

Not imported by production. Prototypes the multi-source story architecture
(banks/packs/pipelines/styles as JSON; Python validates, routes, executes,
fails loudly) and emits the bridge artifact production will consume at the
explicit transplant chunk.
"""

from .contracts import (
    BridgeArtifact,
    LedgerWritingSpec,
    MetaMirrors,
    PipelineSpec,
    PublicDomainSourceManifest,
    Resolution,
    SourceBankSpec,
    SourceMaterialPacket,
    StoryInputPacket,
    StoryPack,
    StoryPromptProfile,
    VisualStylePolicy,
)
from .registry import Registry, RegistryError, UnknownIdError
from .ledger_contract import (
    LedgerContractError,
    LedgerEnvelope,
    OutcomeReceipt,
    ReceiptVerifier,
    ReceiptVerifierKey,
    StoryBody,
    StoryLedger,
    StorySeal,
    accept_production_attempt,
    append_production_attempt,
    assert_production_append_only,
    assert_story_unchanged,
    build_story_seal,
    canonical_bytes,
    canonical_sha256,
    initialize_production_state,
    verify_production_state,
    verify_story_acceptance,
    verify_story_envelope,
)
from .production_contract import (
    AcceptanceEvent,
    ArtifactReceipt,
    ArtifactRef,
    AttemptEvent,
    DependencyRef,
    PHASE_ATTEMPT_TYPES,
    PRODUCTION_PHASE_IDS,
    PRODUCTION_PHASE_OWNERS,
    PRODUCTION_PHASE_REGISTRY,
    PRODUCTION_STATE_SCHEMA_VERSION,
    PhaseAcceptance,
    ProductionContractError,
    ProductionState,
    RunPhase,
    StoryRef,
    active_acceptance,
    default_run_plan,
    production_canonical_bytes,
    production_sha256,
)
from .ledger_verifiers import (
    CAPTURED_SOURCE_PACKET_SCHEMA_VERSION,
    CapturedSourcePacketArtifact,
    TRUSTED_VALIDATOR_IDENTITIES,
    TRUSTED_VALIDATOR_VERSION,
    build_trusted_receipt_verifiers,
    verify_announcer_news_coda,
    verify_announcer_open,
    verify_ledger_integrity,
    verify_music_bookends,
    verify_news_capture,
)

__all__ = [
    "BridgeArtifact",
    "CAPTURED_SOURCE_PACKET_SCHEMA_VERSION",
    "CapturedSourcePacketArtifact",
    "LedgerWritingSpec",
    "LedgerContractError",
    "LedgerEnvelope",
    "MetaMirrors",
    "OutcomeReceipt",
    "PHASE_ATTEMPT_TYPES",
    "PRODUCTION_PHASE_IDS",
    "PRODUCTION_PHASE_OWNERS",
    "PRODUCTION_PHASE_REGISTRY",
    "PRODUCTION_STATE_SCHEMA_VERSION",
    "PipelineSpec",
    "PublicDomainSourceManifest",
    "ReceiptVerifier",
    "ReceiptVerifierKey",
    "Registry",
    "RegistryError",
    "Resolution",
    "SourceBankSpec",
    "SourceMaterialPacket",
    "StoryInputPacket",
    "StoryBody",
    "StoryLedger",
    "StoryPack",
    "StoryPromptProfile",
    "StorySeal",
    "AcceptanceEvent",
    "ArtifactReceipt",
    "ArtifactRef",
    "AttemptEvent",
    "DependencyRef",
    "PhaseAcceptance",
    "ProductionContractError",
    "ProductionState",
    "RunPhase",
    "StoryRef",
    "TRUSTED_VALIDATOR_IDENTITIES",
    "TRUSTED_VALIDATOR_VERSION",
    "UnknownIdError",
    "VisualStylePolicy",
    "accept_production_attempt",
    "active_acceptance",
    "append_production_attempt",
    "assert_production_append_only",
    "assert_story_unchanged",
    "build_story_seal",
    "build_trusted_receipt_verifiers",
    "canonical_bytes",
    "canonical_sha256",
    "default_run_plan",
    "initialize_production_state",
    "production_canonical_bytes",
    "production_sha256",
    "verify_production_state",
    "verify_story_acceptance",
    "verify_story_envelope",
    "verify_announcer_news_coda",
    "verify_announcer_open",
    "verify_ledger_integrity",
    "verify_music_bookends",
    "verify_news_capture",
]
